### ISSUE TITLE
Xcode security warning

### ISSUE THREAD

**Issue by marosabal** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#15]
**Describe the bug**

The client initialization brings a security warning on the Xcode.
I can not also initialize the client on a background thread.

* [X] SPM
* [ ] Cocoapods
* [ ] Direct Download

**SDK Version (e.g. 18.0.2):**

**To Reproduce**

Initialize the SDK using the given [documentation]( https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps ).

**Expected behavior**

Can support thread safety?

**Screenshots**

Main thread initialization:
<img width="520" alt="Screenshot 2022-11-25 at 17 35 43" src="https://user-images.githubusercontent.com/19843260/204027133-ef1b89f1-0b2c-4ffe-b876-b27ade20bfed.png">

Background initialization:

<img width="525" alt="Screenshot 2022-11-25 at 17 49 02" src="https://user-images.githubusercontent.com/19843260/204028394-2d528091-2d16-4507-b331-df913a29fd73.png">

<img width="830" alt="Screenshot 2022-11-25 at 17 45 40" src="https://user-images.githubusercontent.com/19843260/204028090-6bb33e79-750f-444d-8044-d9f83dc0f0b1.png">

**Xcode version:**
 - 14.1 (14B47b)

**Device:**
 - The warning appears both on the simulator and the device.

**Comment by mcorner** [comment]
Thank you for reporting this, we have seen this warning as well.   Our current understanding is that this is an Apple bug in ios 16 or XCode 14.  There are a few threads out there on this, but this is probably the best: https://developer.apple.com/forums/thread/714467

Closing for now as we believe this is harmless and will get fixed by Apple at some point.  Please reopen if needed.
